In [1]:
import psycopg
import os
from sqlalchemy import create_engine, text
import urllib.parse
import json

database = os.getenv("POSTGRES_DB")
user = os.getenv("POSTGRES_USER")
password = os.getenv("POSTGRES_PASSWORD")
host = os.getenv("POSTGRES_HOST")
port=os.getenv("POSTGRES_PORT")

password = urllib.parse.quote_plus(password)

engine = create_engine(
    "postgresql+psycopg://postgres:postgres@localhost:5433/postgres_crypto"
)

with engine.connect() as conn:
    result_trade = conn.execute(text("SELECT * FROM trade_agg_1min;"))
    result_ob = conn.execute(text("SELECT * FROM ob_agg_1min;"))

In [2]:
import pandas as pd
data_df = [dict(row._mapping) for row in result_trade]
df_trade = pd.DataFrame(data_df)
df_trade

,window_start,symbol,open_price,high_price,low_price,close_price,total_qty,vwap,buy_qty,sell_qty
0,2026-04-20 08:36:00,BTCUSDT,74892.98,74893.67,74874.40,74892.98,6.10530,74889.874199,3.18811,2.91719
1,2026-04-20 08:21:00,BTCUSDT,74954.14,74987.20,74880.61,74954.14,11.84564,74928.904305,5.56554,6.28010
2,2026-04-20 08:22:00,BTCUSDT,74935.51,74942.34,74872.45,74935.51,7.91824,74901.520920,2.41281,5.50543
3,2026-04-20 08:16:00,BTCUSDT,74852.52,74875.61,74845.51,74852.52,2.01385,74864.383747,1.52259,0.49126
4,2026-04-20 08:10:00,BTCUSDT,74671.40,74765.27,74671.40,74671.40,10.97080,74705.539333,9.51987,1.45093
5,2026-04-20 08:09:00,BTCUSDT,74709.26,74709.26,74664.52,74709.26,17.94021,74668.620611,14.34114,3.59907
6,2026-04-20 08:06:00,BTCUSDT,74692.00,74710.42,74676.83,74692.00,5.26818,74692.173697,3.19701,2.07117
7,2026-04-20 08:14:00,BTCUSDT,74840.81,74876.01,74811.54,74840.81,5.33837,74842.156183,3.40943,1.92894
8,2026-04-20 08:25:00,BTCUSDT,74838.98,74838.98,74793.22,74838.98,13.51933,74805.891230,3.35944,10.15989
9,2026-04-20 08:24:00,BTCUSDT,74865.02,74865.47,74837.28,74865.02,4.38061,74850.947657,3.00629,1.37432
10,2026-04-20 08:23:00,BTCUSDT,74874.07,74902.87,74865.02,74874.07,9.47811,74880.455561,6.72890,2.74921
11,2026-04-20 08:41:00,BTCUSDT,74763.99,74788.09,74763.98,74763.99,3.18680,74771.238268,2.54624,0.64056
12,2026-04-20 08:28:00,BTCUSDT,74788.69,74807.11,74767.94,74788.69,5.37036,74775.683874,3.52163,1.84873
13,2026-04-20 08:27:00,BTCUSDT,74737.99,74801.80,74737.99,74737.99,9.07192,74769.281322,1.89357,7.17835
14,2026-04-20 08:26:00,BTCUSDT,74797.27,74797.27,74713.97,74797.27,7.63823,74746.200563,3.18054,4.45769
15,2026-04-20 08:13:00,BTCUSDT,74790.96,74840.82,74790.21,74790.96,13.51951,74812.012215,12.33589,1.18362
16,2026-04-20 08:15:00,BTCUSDT,74887.99,74887.99,74852.51,74887.99,1.17697,74870.810218,0.10096,1.07601
17,2026-04-20 08:34:00,BTCUSDT,74887.73,74913.81,74885.72,74887.73,3.11192,74894.638711,1.70558,1.40634
18,2026-04-20 08:29:00,BTCUSDT,74800.59,74827.22,74789.29,74800.59,5.60832,74810.681062,3.32783,2.28049
19,2026-04-20 08:07:00,BTCUSDT,74710.43,74749.29,74698.12,74710.43,7.97319,74728.716050,3.38740,4.58579
20,2026-04-20 08:12:00,BTCUSDT,74760.38,74790.96,74740.57,74760.38,9.36567,74759.582028,8.84943,0.51624
21,2026-04-20 08:30:00,BTCUSDT,74817.72,74838.00,74805.22,74817.72,3.92583,74819.867677,1.93649,1.98934
22,2026-04-20 08:31:00,BTCUSDT,74809.67,74809.68,74775.99,74809.67,4.14363,74789.344413,2.69827,1.44536
23,2026-04-20 08:19:00,BTCUSDT,74931.99,74998.83,74925.80,74931.99,15.25436,74968.786117,14.39514,0.85922
24,2026-04-20 08:39:00,BTCUSDT,74810.60,74810.61,74758.86,74810.60,22.65985,74777.020896,3.39185,19.26800
25,2026-04-20 08:47:00,BTCUSDT,74764.00,74789.74,74763.99,74764.00,10.72392,74773.130321,7.16379,3.56013
26,2026-04-20 08:18:00,BTCUSDT,74896.88,74932.00,74885.22,74896.88,12.77870,74903.411277,8.25723,4.52147
27,2026-04-20 08:08:00,BTCUSDT,74698.12,74744.64,74697.17,74698.12,8.10953,74724.136512,2.00480,6.10473
28,2026-04-20 08:45:00,BTCUSDT,74835.51,74859.73,74835.51,74835.51,8.56439,74844.166815,7.03687,1.52752
29,2026-04-20 08:11:00,BTCUSDT,74765.26,74775.96,74744.84,74765.26,4.66821,74763.036797,2.77380,1.89441
30,2026-04-20 08:43:00,BTCUSDT,74831.60,74831.61,74820.71,74831.60,6.61988,74825.817409,5.99138,0.62850
31,2026-04-20 08:20:00,BTCUSDT,74993.26,74993.27,74943.72,74993.26,11.75802,74958.171021,6.48317,5.27485
32,2026-04-20 08:46:00,BTCUSDT,74835.52,74835.52,74763.99,74835.52,3.23031,74797.880169,0.76184,2.46847
33,2026-04-20 08:32:00,BTCUSDT,74805.00,74931.35,74792.63,74805.00,31.58876,74857.566773,22.92163,8.66713
34,2026-04-20 08:17:00,BTCUSDT,74854.83,74896.92,74846.00,74854.83,9.14341,74862.974681,5.81776,3.32565
35,2026-04-20 08:37:00,BTCUSDT,74879.40,74879.40,74845.26,74879.40,2.49678,74862.316174,1.08600,1.41078
36,2026-04-20 08:48:00,BTCUSDT,74781.07,74781.08,74781.07,74781.07,0.12834,74781.070051,0.00065,0.12769
37,2026-04-20 08:40:00,BTCUSDT,74784.18,74784.19,74751.00,74784.18,3.01915,74763.171434,1.68797,1.33118
38,2026-04-20 08:35:00,BTCUSDT,74886.41,74892.98,74853.33,74886.41,4.84395,74866.280617,2.47407,2.36988
39,2026-04-20 08:33:00,BTCUSDT,74931.34,74931.35,74887.73,74931.34,6.68340,74909.735989,3.78812,2.89528
40,2026-04-20 08:44:00,BTCUSDT,74824.94,74845.56,74814.67,74824.94,9.26247,74829.420670,6.35176,2.91071
41,2026-04-20 08:42:00,BTCUSDT,74788.08,74831.62,74788.08,74788.08,3.93385,74819.014829,2.76107,1.17278
42,2026-04-20 08:38:00,BTCUSDT,74845.26,74846.08,74810.60,74845.26,3.25068,74836.599557,1.86433,1.38635

In [3]:
data_df = [dict(row._mapping) for row in result_ob]
df_ob = pd.DataFrame(data_df)
df_ob

,window_start,symbol,bid_liquidity,ask_liquidity,total_liquidity,imbalance,vwap
0,2026-04-20 08:18:00,BTCUSDT,0.0,0.0,2274.22525,0.0,74899.923183
1,2026-04-20 08:31:00,BTCUSDT,0.0,0.0,3484.93264,0.0,74792.835225
2,2026-04-20 08:16:00,BTCUSDT,0.0,0.0,2518.81096,0.0,74860.144410
3,2026-04-20 08:08:00,BTCUSDT,0.0,0.0,3182.52214,0.0,74722.805755
4,2026-04-20 08:11:00,BTCUSDT,0.0,0.0,2884.72018,0.0,74755.664274
5,2026-04-20 08:48:00,BTCUSDT,0.0,0.0,770.70618,0.0,74781.052936
6,2026-04-20 08:38:00,BTCUSDT,0.0,0.0,3847.77570,0.0,74841.029181
7,2026-04-20 08:39:00,BTCUSDT,0.0,0.0,4145.14401,0.0,74778.354620
8,2026-04-20 08:20:00,BTCUSDT,0.0,0.0,3194.41908,0.0,74962.411638
9,2026-04-20 08:07:00,BTCUSDT,0.0,0.0,3139.01360,0.0,74729.462615
10,2026-04-20 08:37:00,BTCUSDT,0.0,0.0,3324.89900,0.0,74866.777333
11,2026-04-20 08:34:00,BTCUSDT,0.0,0.0,3267.29374,0.0,74894.497727
12,2026-04-20 08:12:00,BTCUSDT,0.0,0.0,3298.27515,0.0,74758.000096
13,2026-04-20 08:43:00,BTCUSDT,0.0,0.0,2463.47025,0.0,74827.265789
14,2026-04-20 08:06:00,BTCUSDT,0.0,0.0,1823.43309,0.0,74692.491499
15,2026-04-20 08:23:00,BTCUSDT,0.0,0.0,3095.17768,0.0,74890.080375
16,2026-04-20 08:25:00,BTCUSDT,0.0,0.0,3735.26303,0.0,74818.818102
17,2026-04-20 08:24:00,BTCUSDT,0.0,0.0,3166.96598,0.0,74855.620904
18,2026-04-20 08:26:00,BTCUSDT,0.0,0.0,3475.12143,0.0,74758.441215
19,2026-04-20 08:40:00,BTCUSDT,0.0,0.0,3482.30782,0.0,74771.014678
20,2026-04-20 08:22:00,BTCUSDT,0.0,0.0,3255.12205,0.0,74909.685842
21,2026-04-20 08:47:00,BTCUSDT,0.0,0.0,4076.19429,0.0,74776.167196
22,2026-04-20 08:41:00,BTCUSDT,0.0,0.0,2842.30543,0.0,74773.374739
23,2026-04-20 08:32:00,BTCUSDT,0.0,0.0,4409.62920,0.0,74834.908201
24,2026-04-20 08:17:00,BTCUSDT,0.0,0.0,3269.04993,0.0,74865.451328
25,2026-04-20 08:15:00,BTCUSDT,0.0,0.0,2914.50734,0.0,74847.104800
26,2026-04-20 08:13:00,BTCUSDT,0.0,0.0,3606.75408,0.0,74802.923000
27,2026-04-20 08:27:00,BTCUSDT,0.0,0.0,3539.59875,0.0,74770.324785
28,2026-04-20 08:19:00,BTCUSDT,0.0,0.0,4099.33688,0.0,74955.046160
29,2026-04-20 08:36:00,BTCUSDT,0.0,0.0,2828.88261,0.0,74891.997938
30,2026-04-20 08:46:00,BTCUSDT,0.0,0.0,3663.29555,0.0,74804.664373
31,2026-04-20 08:28:00,BTCUSDT,0.0,0.0,3408.60945,0.0,74786.411741
32,2026-04-20 08:21:00,BTCUSDT,0.0,0.0,3709.19798,0.0,74923.469826
33,2026-04-20 08:14:00,BTCUSDT,0.0,0.0,3320.55641,0.0,74850.781241
34,2026-04-20 08:10:00,BTCUSDT,0.0,0.0,3689.13092,0.0,74701.683283
35,2026-04-20 08:09:00,BTCUSDT,0.0,0.0,4948.66559,0.0,74685.726458
36,2026-04-20 08:29:00,BTCUSDT,0.0,0.0,3791.65438,0.0,74804.645317
37,2026-04-20 08:45:00,BTCUSDT,0.0,0.0,3494.56686,0.0,74842.440700
38,2026-04-20 08:30:00,BTCUSDT,0.0,0.0,3508.54757,0.0,74821.006439
39,2026-04-20 08:33:00,BTCUSDT,0.0,0.0,3206.14008,0.0,74910.213681
40,2026-04-20 08:35:00,BTCUSDT,0.0,0.0,3919.36528,0.0,74869.013542
41,2026-04-20 08:44:00,BTCUSDT,0.0,0.0,3103.39321,0.0,74828.579677
42,2026-04-20 08:42:00,BTCUSDT,0.0,0.0,2329.53350,0.0,74814.784647

In [ ]:
from Kronos.model import Kronos, KronosTokenizer, KronosPredictor

tokenizer = KronosTokenizer.from_pretrained("NeoQuasar/Kronos-Tokenizer-base")
model = Kronos.from_pretrained("NeoQuasar/Kronos-small")

predictor = KronosPredictor(model, tokenizer, max_context=512)

In [4]:
crypto_data = df_trade[['window_start', 'open_price', 'high_price', 'low_price', 'close_price', 'total_qty']]
crypto_data.columns = ['timestamp', 'open', 'high', 'low', 'close', 'volume']
crypto_data['timestamp'] = pd.to_datetime(crypto_data['timestamp'])

In [ ]:
lookback = 400
pred_len = 60

x_df = df.iloc[:lookback][['open','high','low','close','volume']]
x_timestamp = df.iloc[:lookback]['timestamp']

y_timestamp = df.iloc[lookback:lookback+pred_len]['timestamp']

In [ ]:
pred_df = predictor.predict(
    df=x_df,
    x_timestamp=x_timestamp,
    y_timestamp=y_timestamp,
    pred_len=pred_len
)

print(pred_df.head())